// automatically generated by the FlatBuffers compiler, do not modify


{% for item in __fbs_meta__['tables'] %}
{% set table_name = item.__name__ %}

public interface {{table_name}} {
{% for member, type in item['_fspec'].items() %}
{% set java_type = java_types[type[1]] %}

  @Field(R.schema.{{namespace}}.{{member}})
  {{java_type}} get{{member}}();
{% endfor %}
};


{% endfor %}


