# automatically generated by the FlatBuffers compiler, do not modify
from ctypes import (
    c_int16 as int16,
    c_uint64 as uint64,
    c_int8 as int8,
)
from dataclasses import dataclass


class Color(Enum):
    Red = 1
    Green = 2
    Blue = 3


@dataclass
class Person:
    name: str
    address: str
    age: int16
    length: uint64
    favorite_color: Color


@dataclass
class Product:
    label: str
    price: int


Item = Union[Product, Person]
