# automatically generated by the FlatBuffers compiler, do not modify
from ctypes import (
    c_int16 as int16,
    c_uint64 as uint64,
    c_int16 as int16,
    c_int8 as int8,
)
from dataclasses import dataclass
from typing import Protocol

from enum import Enum
from typing import Union


class Color(Enum):
    Red = 1
    Green = 2
    Blue = 3

class NamedAnimal(Protocol):
    name: str
    age: int16

@dataclass
class Animal:
    name: str
    length: uint64

@dataclass
class Person(Animal):
    address: str
    age: int16
    favorite_color: "Color"

@dataclass
class Product:
    label: str
    price: int


Item = Union[Product, Person]
