# automatically generated by the FlatBuffers compiler, do not modify
{% set cint_types = c_int_types() %}
{% if cint_types|length %}
from ctypes import (
{% endif %}
{% for int_type in cint_types %}
    c_{{int_type}} as {{int_type}},
{% endfor %}
{% if cint_types|length %}
)
{% endif %}
from dataclasses import dataclass

@dataclass
{% set table_name = table.__name__ %}
class {{table_name}}:
{% for member, type in table['_fspec'].items() %}
{% set py_type = get_type(type[1]) %}
    {{member}}: {{py_type}}
{% endfor %}

