# automatically generated by the FlatBuffers compiler, do not modify
from dataclasses import dataclass

{% for item in __fbs_meta__['tables'] %}
@dataclass
{% set table_name = item.__name__ %}
class {{table_name}}:
{% for member, type in item['_fspec'].items() %}
{% set py_type = get_type(type[1]) %}
    {{member}}: {{py_type}}
{% endfor %}
{% endfor %}

