// automatically generated by the FlatBuffers compiler, do not modify

{% for item in __fbs_meta__['enums'] %}
{% set enum_name = item.__name__ %}

public enum {{enum_name}} {
{% for member, value in item['_NAMES_TO_VALUES'].items() %}
{% if value is none %}
  {{member}},
{% else %}
  {{member}}({{value}}),
{% endif %}
{% endfor %}
};

{% endfor %}

{% for item in __fbs_meta__['tables'] %}
{% set table_name = item.__name__ %}

public interface {{table_name}} {
{% for member, type in item['_fspec'].items() %}
{% set java_type = get_type(type[1]) %}

  @Field(R.schema.{{namespace}}.{{member}})
  {{java_type}} get{{member}}();
{% endfor %}
};


{% endfor %}


